### ISSUE TITLE
Task1 #3 needs a relook

### ISSUE THREAD

**Issue by dpkshetty** [Castro38/automatic-ml-intro-tutorial-h2oai#2]
Task1 #3 says ...
"3. Log in by creating a unique username/password. Save your username and password so you can return to the experiments you have worked on."

Based on my usage of the H2O, i have never seen a "Sign Up" button, it always has a "Sign In" button, the picture in the readme also shows Sign In.. so #3 should rather provide the login creds and not indicate to create a new login... as there is no way (afaik) to create a new login

**Comment by Castro38** [comment]
Hi @dpkshetty, thank you for your feedback. Your suggestions have been incorporated to our [1.5.2 Automatic ML Intro Tutorial](https://github.com/h2oai/tutorials/blob/master/DriverlessAI/automatic-ml-intro-tutorial/automatic-ml-intro-tutorial.md).
